runtime: python38
instance_class: F4_1G
entrypoint: gunicorn -b :8080 -w 1 main:app



#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT main:app
#
#runtime_config:
#  python_version: 3.7
#
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 2
#  memory_gb: 2
#  disk_size_gb: 10