columns = ['weekend',
          'price',
          'description_len',
          'title_len',
          'param_1_len',
          'param_2_len',
          'param_3_len',
          'region_en_Bashkortostan',
          'region_en_Belgorod oblast',
          'region_en_Chelyabinsk oblast',
          'region_en_Irkutsk oblast',
          'region_en_Kaliningrad oblast',
          'region_en_Kemerovo oblast',
          'region_en_Khanty-Mansi Autonomous Okrug',
          'region_en_Krasnodar Krai',
          'region_en_Krasnoyarsk Krai',
          'region_en_Nizhny Novgorod oblast',
          'region_en_Novosibirsk oblast',
          'region_en_Omsk oblast',
          'region_en_Orenburg oblast',
          'region_en_Perm Krai',
          'region_en_Rostov oblast',
          'region_en_Samara oblast',
          'region_en_Saratov oblast',
          'region_en_Stavropol Krai',
          'region_en_Sverdlovsk oblast',
          'region_en_Tatarstan',
          'region_en_Tula oblast',
          'region_en_Tyumen oblast',
          'region_en_Udmurtia',
          'region_en_Vladimir oblast',
          'region_en_Volgograd oblast',
          'region_en_Voronezh oblast',
          'region_en_Yaroslavl oblast',
          'user_type_Private',
          'user_type_Shop',
          'category_name_en_Appliances',
          'category_name_en_Aquarium',
          'category_name_en_Audio and video',
          'category_name_en_Bikes',
          'category_name_en_Birds',
          'category_name_en_Books and magazines',
          'category_name_en_Cars',
          'category_name_en_Cats',
          'category_name_en_Children\'s clothing and shoes',
          'category_name_en_Children\'s products and toys',
          'category_name_en_Clothing, shoes, accessories',
          'category_name_en_Collecting',
          'category_name_en_Commercial property',
          'category_name_en_Desktop computers',
          'category_name_en_Dogs',
          'category_name_en_Equipment for business',
          'category_name_en_Food',
          'category_name_en_Furniture and interior',
          'category_name_en_Games, consoles and software',
          'category_name_en_Garages and Parking spaces',
          'category_name_en_Health and beauty',
          'category_name_en_Houses, villas, cottages',
          'category_name_en_Hunting and fishing',
          'category_name_en_Land',
          'category_name_en_Laptops',
          'category_name_en_Motorcycles and bikes',
          'category_name_en_Musical instruments',
          'category_name_en_Offer services',
          'category_name_en_Office equipment and consumables',
          'category_name_en_Other animals',
          'category_name_en_Pet products',
          'category_name_en_Phones',
          'category_name_en_Photo',
          'category_name_en_Plants',
          'category_name_en_Products for computer',
          'category_name_en_Property abroad',
          'category_name_en_Ready business',
          'category_name_en_Repair and construction',
          'category_name_en_Room',
          'category_name_en_Sports and recreation',
          'category_name_en_Tablets and e-books',
          'category_name_en_Tableware and goods for kitchen',
          'category_name_en_Tickets and travel',
          'category_name_en_Trucks and buses',
          'category_name_en_Watches and jewelry',
          'category_name_en_Water transport']