apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: avito-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: avito-server
    spec:
      containers:
      - name: avito-container
        image: gcr.io/tensorflow-283115/avito
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: avito-service
  name: avito-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: avito-server
  type: LoadBalancer
